name: Workflow
on:
  push:
    branches: [ main ]
    tags:
      - v**
  pull_request: { }

permissions:
  contents: read

jobs:
  required-meta:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v2

  check-commits:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v4
    with:
      build-tool: uv
      python-version: '3.14'

  lint:
    strategy:
      matrix:
        pyversion: [ "3.13", "3.14" ]
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v6
    with:
      build-tool: uv
      python-version: ${{ matrix.pyversion }}

  test:
    strategy:
      matrix:
        pyversion: [ "3.13", "3.14" ]
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v6
    with:
      build-tool: uv
      python-version: ${{ matrix.pyversion }}
      submit-coverage: ${{ matrix.pyversion == '3.13' }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  all-checks-passed:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    needs:
      - check-commits
      - lint
      - test
    steps:
      - run: echo 'All checks passed'

  bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v4
    needs:
      - lint
      - test
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    with:
      build-tool: uv
      python-version: '3.14'

  publish_package:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/publish-package.yml@v6
    needs:
      - lint
      - test
    if: success() && startsWith(github.ref, 'refs/tags/v')
    with:
      build-tool: uv
      python-version: '3.13'
      pypi-username: ${{ vars.PYPI_USERNAME }}
    secrets:
      pypi-password: ${{ secrets.PYPI_PASSWORD }}
